<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.jiahuiling</groupId>
        <artifactId>xiaojiashu</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>xiaojia-framework</artifactId>
    <packaging>pom</packaging>

    <name>xiaojia-framework</name>
    <modules>
        <module>xiaojia-common</module>
        <module>xiaojia-spring-boot-starter-biz-operationlog</module>
        <module>xiaojia-spring-boot-starter-jackson</module>
        <module>xiaojia-spring-boot-starter-biz-context</module>
    </modules>

</project>
