spring:
  #DevTools 重启 + JMX Admin MBean 重复注册 的问题
  devtools:
    restart:
      trigger-file: .reloadtrigger
      poll-interval: 2s
      quiet-period: 1s
      additional-exclude: "logs/**,static/**,public/**,templates/**"

  data:
    redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      password: qwe123!@#
      timeout: 5s
      connect-timeout: 5s
      lettuce:
        pool:
          max-active: 200
          max-wait: -1ms
          min-idle: 0
          max-idle: 10
