<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.jiahuiling</groupId>
        <artifactId>xiaojiashu-user</artifactId>
        <version>${revision}</version>
    </parent>

    <groupId>com.jiahuiling.xiaojiashu.user.api</groupId>
    <artifactId>xiaojiashu-user-api</artifactId>
    <packaging>jar</packaging>

    <name>${project.artifactId}</name>
    <url>http://maven.apache.org</url>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <description>RPC层, 供其他服务调用</description>

    <dependencies>
        <dependency>
            <groupId>com.jiahuiling</groupId>
            <artifactId>xiaojia-common</artifactId>
        </dependency>
    </dependencies>
</project>
