<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.jiahuiling</groupId>
        <artifactId>xiaojiashu</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>xiaojiashu-user-relation</artifactId>
    <packaging>pom</packaging>

    <!-- 项目名称 -->
    <name>${project.artifactId}</name>
    <!-- 项目描述 -->
    <description>用户关系服务</description>
    <url>http://maven.apache.org</url>
    <modules>
        <module>xiaojiashu-user-relation-api</module>
        <module>xiaojiashu-user-relation-biz</module>
    </modules>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

</project>
